// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Username string `json:"username"`
	Passwrod string `json:"password"`
}

type LoginReply struct {
	Token string `json:"token"`
}
