// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package sys_user_model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysUser = "sys_user"

// SysUser mapped from table <sys_user>
type SysUser struct {
	ID           int64          `gorm:"column:id;primaryKey" json:"id"`
	Username     string         `gorm:"column:username" json:"username"`
	Password     string         `gorm:"column:password" json:"password"`
	CreatedAt    time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Nickname     string         `gorm:"column:nickname" json:"nickname"`
	Salt         string         `gorm:"column:salt" json:"salt"`
	Phone        string         `gorm:"column:phone" json:"phone"`
	Gender       int16          `gorm:"column:gender" json:"gender"` // 性别，0：女，1：男，默认1
	Head         string         `gorm:"column:head" json:"head"`
	Remark       string         `gorm:"column:remark" json:"remark"`
	State        int16          `gorm:"column:state" json:"state"`                 // 状态，0：禁用，1：启用，2：锁定
	DepartmentID int64          `gorm:"column:department_id" json:"department_id"` // 部门id
	RoleID       int64          `gorm:"column:role_id" json:"role_id"`
	Eamil        string         `gorm:"column:eamil" json:"eamil"`
}

// TableName SysUser's table name
func (*SysUser) TableName() string {
	return TableNameSysUser
}
