// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package user_client

import (
	"context"

	"go-zero-micro/service/user/rpc/types/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CheckUserRequest  = user.CheckUserRequest
	CheckUserResponse = user.CheckUserResponse
	IdRequest         = user.IdRequest
	UserPageReq       = user.UserPageReq
	UserPageRes       = user.UserPageRes
	UserResponse      = user.UserResponse

	User interface {
		GetUser(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*UserResponse, error)
		CheckUser(ctx context.Context, in *CheckUserRequest, opts ...grpc.CallOption) (*CheckUserResponse, error)
		UserLogin(ctx context.Context, in *CheckUserRequest, opts ...grpc.CallOption) (*UserResponse, error)
		UserPage(ctx context.Context, in *UserPageReq, opts ...grpc.CallOption) (*UserPageRes, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) GetUser(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

func (m *defaultUser) CheckUser(ctx context.Context, in *CheckUserRequest, opts ...grpc.CallOption) (*CheckUserResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.CheckUser(ctx, in, opts...)
}

func (m *defaultUser) UserLogin(ctx context.Context, in *CheckUserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UserLogin(ctx, in, opts...)
}

func (m *defaultUser) UserPage(ctx context.Context, in *UserPageReq, opts ...grpc.CallOption) (*UserPageRes, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UserPage(ctx, in, opts...)
}
