// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"go-zero-micro/service/gateway/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/login",
				Handler: loginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/user",
				Handler: createUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/:id",
				Handler: getUserHandler(serverCtx),
			},
		},
	)
}
