// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package sys_department_model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysDepartment = "sys_department"

// SysDepartment mapped from table <sys_department>
type SysDepartment struct {
	ID        int64          `gorm:"column:id;primaryKey" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Name      string         `gorm:"column:name" json:"name"`
	State     int16          `gorm:"column:state" json:"state"`
	Remark    string         `gorm:"column:remark" json:"remark"`
	ParentID  int64          `gorm:"column:parent_id" json:"parent_id"`
}

// TableName SysDepartment's table name
func (*SysDepartment) TableName() string {
	return TableNameSysDepartment
}
