// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginReply struct {
	Token string `json:"token"`
}

type CreateUserReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Nickname string `json:"nickname"`
	Phone    string `json:"phone"`
	Gender   int16  `json:"gender"`
	Head     string `json:"head"`
	Remark   string `json:"remark"`
	Eamil    string `json:"eamil"`
}

type UserReply struct {
	Username string `json:"username"`
	Nickname string `json:"nickname"`
	Phone    string `json:"phone"`
	Gender   int16  `json:"gender"`
	Head     string `json:"head"`
	Remark   string `json:"remark"`
	Eamil    string `json:"eamil"`
}

type GetProductReq struct {
	Id string `path:"id"`
}
